services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: 'frontend-service'
    ports:
      - 3000:3000
    stdin_open: true
    env_file:
      - ./apps/frontend/.env    
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        SERVICE_NAME: backend
    container_name: 'backend-service'
    ports:
      - 3001:3000
    stdin_open: true
    env_file:
      - ./apps/backend/.env
  microservice:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        SERVICE_NAME: microservice
    container_name: 'microservice-service'
    ports:
      - 3002:3000
    stdin_open: true
    env_file:
      - ./apps/microservice/.env    