# BASE STAGE
FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# INSTALL STAGE
FROM base AS install
WORKDIR /app
ARG SERVICE_NAME
COPY turbo.json pnpm-workspace.yaml package.json ./
COPY ./packages ./packages
COPY ./apps/${SERVICE_NAME} ./apps/${SERVICE_NAME}
RUN pnpm config set inject-workspace-packages=true
RUN pnpm install 

# BUILD STAGE
FROM install AS build
WORKDIR /app
ARG SERVICE_NAME
RUN pnpm build:packages
RUN pnpm --filter=./apps/${SERVICE_NAME} build
RUN pnpm deploy --filter=./apps/${SERVICE_NAME} --prod /prod

# RUNNER STAGE
FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1
RUN npm i -g @nestjs/cli
COPY --from=build /prod /app
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nestjs
RUN chown -R nestjs:nodejs /app
USER nestjs
EXPOSE 3000
CMD ["npm", "run", "start:prod"]

