# BASE STAGE
FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# INSTALL STAGE
FROM base AS install
WORKDIR /app
COPY turbo.json pnpm-workspace.yaml package.json ./
COPY ./packages ./packages
COPY ./apps/frontend ./apps/frontend
RUN pnpm config set inject-workspace-packages=true
RUN pnpm install 

# BUILD STAGE
FROM install AS build
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED 1
RUN pnpm build:packages
RUN pnpm --filter=./apps/frontend build
RUN pnpm deploy --filter=./apps/frontend --prod /prod

# RUNNER STAGE
FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# You only need to copy next.config.js if you are NOT using the default configuration
COPY --from=build /prod /app
USER nextjs
EXPOSE 3000
ENV PORT 3000

CMD ["npm", "start"]